name: Gradle Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Клонируем репозиторий
      - uses: actions/checkout@v3

      # Устанавливаем JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Устанавливаем Chrome stable и подходящий ChromeDriver
      - name: Set up Chrome stable
        uses: browser-actions/setup-chrome@v2
        with:
          chrome-version: 'stable'
          install-chromedriver: true

      # Делаем gradlew исполняемым
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Запускаем SUT (приложение)
      - name: Start SUT
        run: java -jar ./artifacts/app-card-delivery.jar &
      
      # Даем время на старт приложения
      - name: Wait for SUT
        run: sleep 10

      # Запускаем тесты через Gradle в headless режиме
      - name: Run Gradle tests
        run: ./gradlew test --info -Dselenide.headless=true
